### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by elias-Mimetrik** [andresprados/SPIGA#13]
Error when running the demo app.py

I install the latest pytorch from https://pytorch.org/:
```pip3 install torch torchvision torchaudio```

Then I run the install instructions:
```
pip install -e .  
pip install -e .[demo]
```
The error I get is:
```
app.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Loading pretrained model from https://drive.google.com/uc?export=download&confirm=yes&id=1nxhtpdVLbmheUTwyIb733MrL53X4SQgQ
Traceback (most recent call last):
  File "app.py", line 107, in <module>
    main()
  File "app.py", line 47, in main
    video_app(args.input, spiga_dataset=args.dataset, tracker=args.tracker, fps=args.fps,
  File "app.py", line 80, in video_app
    faces_tracker = tr.get_tracker(tracker)
  File "/home/user/eclipse-workspace/111_SPIGA (face landmark detection)/spiga/demo/analyze/track/get_tracker.py", line 9, in get_tracker
    model = zoo.get_tracker(model_name)
  File "/home/user/eclipse-workspace/111_SPIGA (face landmark detection)/spiga/demo/analyze/track/retinasort/zoo.py", line 10, in get_tracker
    return tr.RetinaSortTracker()
  File "/home/user/eclipse-workspace/111_SPIGA (face landmark detection)/spiga/demo/analyze/track/retinasort/face_tracker.py", line 18, in __init__
    self.detector = retinaface.RetinaFaceDetector(model=config['retina']['model_name'],
  File "/home/user/miniconda3/envs/SPIGA5/lib/python3.8/site-packages/retinaface/inference_framework.py", line 48, in __init__
    net = rf_detect.load_model(net, trained_model, cpu_flag, url_file_name=url_model_name)
  File "/home/user/miniconda3/envs/SPIGA5/lib/python3.8/site-packages/retinaface/detect.py", line 47, in load_model
    device = torch.cuda.current_device()
  File "/home/user/miniconda3/envs/SPIGA5/lib/python3.8/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/user/miniconda3/envs/SPIGA5/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

During installation, all nvidia necessary packages are installed:
```
Installing collected packages: mpmath, lit, cmake, zipp, typing-extensions, threadpoolctl, sympy, six, 
scipy, pyparsing, packaging, opencv-python, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, 
nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, 
nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, networkx, MarkupSafe, kiwisolver, joblib, fonttools, filelock, 
cycler, contourpy, scikit-learn, python-dateutil, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, 
importlib-resources, matplotlib, triton, torch, torchaudio, spiga
```

I tried installing older versions of pytorch without any luck. Any ideas please?

**Comment by elias-Mimetrik** [comment]
I managed to get it to work after I reinstalled nvidia drivers from http://www.nvidia.com/Download/index.aspx (not through the official ubuntu channel in software update)
