### ISSUE TITLE
sort_tracker and retinaface not found

### ISSUE THREAD

**Issue by wenzhengzeng** [andresprados/SPIGA#8]
Thanks for your great work. It seems that some of the necessary modules are missing here to run the demo. 
Traceback (most recent call last):
  File "/data1/zengwenzheng/code/SPIGA/./spiga/demo/app.py", line 7, in <module>
    import spiga.demo.analyze.track.get_tracker as tr
  File "/data1/zengwenzheng/code/SPIGA/spiga/demo/analyze/track/get_tracker.py", line 2, in <module>
    import spiga.demo.analyze.track.retinasort.zoo as zoo_rs
  File "/data1/zengwenzheng/code/SPIGA/spiga/demo/analyze/track/retinasort/zoo.py", line 2, in <module>
    import spiga.demo.analyze.track.retinasort.face_tracker as tr
  File "/data1/zengwenzheng/code/SPIGA/spiga/demo/analyze/track/retinasort/face_tracker.py", line 4, in <module>
    import sort_tracker
ModuleNotFoundError: No module named 'sort_tracker'

Can you help me to figure out this issue？ Thanks.

**Comment by wenzhengzeng** [comment]
I missed the pip intall .e [demo]. The issue has been solved。
